### PR TITLE
using deck.js coming from the swcarpentrystyles repository

### PR DESCRIPTION
**Pull request by twitwi**
NB: this is operational only in conjunction with
https://github.com/swcarpentry/styles/pull/30
and the merge of style

### CODE REVIEW

**Comment by rgaiacs** [comment]
@gvwilson Can you merge https://github.com/swcarpentry/styles/ into https://github.com/swcarpentry/slideshows/ and after that merge this pull request?

**Comment by twitwi** [comment]
@r-gaia-cs @gvwilson I kind of lost the big picture lately, should this "styles" also be merged in the lesson-template?

**Comment by rgaiacs** [comment]
> should this "styles" also be merged in the lesson-template?

Yes. I forgot that we have slides on lessons.

**Comment by gvwilson** [comment]
@r-gaia-cs can you please merge?

**Comment by rgaiacs** [comment]
@gvwilson I doesn't have permission to merge this one.

**Comment by gvwilson** [comment]
should now be fixed

On 2015-05-06 4:45 PM, Raniere Silva wrote:

> @gvwilson https://github.com/gvwilson I doesn't have permission to 
> merge this one.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/slideshows/pull/25#issuecomment-99604139.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by twitwi** [comment]
This PR now also fixes #23 and #24 
I didn't want to multiply the number of branches and PR.

**Comment by twitwi** [comment]
@r-gaia-cs @gvwilson I don't know/remember the policy about merging. Let me know if I should self-merge such PR.

**Comment by twitwi** [comment]
@r-gaia-cs,  swcarpentry/styles#30 should be "merged" also for this to work,
what is the procedure to "merge" the "style" repo into another one?

**Comment by rgaiacs** [comment]
@twitwi thanks for the comment. I just found it by my self. I already merge styles and push to this repo. Could you check that everything is OK?

**Comment by twitwi** [comment]
That's ok (the slideshows display properly now).
It does not include the latest changes (https://github.com/swcarpentry/styles/pull/31) but these can wait.
Thanks.

**Pull request merged**
